"""Add chat_history table

Revision ID: 11c30dbd3634
Revises: 50b6e446488c
Create Date: 2025-04-13 21:08:34.729733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c30dbd3634'
down_revision = '50b6e446488c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
