"""add chat_suggested_courses table

Revision ID: 42cff09a305c
Revises: f43698062255
Create Date: 2025-04-28 01:31:30.353668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cff09a305c'
down_revision = 'f43698062255'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
