"""Add chat_history table

Revision ID: 50b6e446488c
Revises: 41c5d192f495
Create Date: 2025-04-13 20:22:59.971081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b6e446488c'
down_revision = '41c5d192f495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
