"""create chat_history table

Revision ID: ca93aa5d1a81
Revises: 6e8d165e27b3
Create Date: 2025-04-26 21:02:03.377468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca93aa5d1a81'
down_revision = '6e8d165e27b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
