"""add chat_suggested_courses table

Revision ID: cff5e8520dd4
Revises: 089484374200
Create Date: 2025-04-28 01:27:23.012241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff5e8520dd4'
down_revision = '089484374200'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
