"""add chat_suggested_courses table

Revision ID: f43698062255
Revises: cff5e8520dd4
Create Date: 2025-04-28 01:28:03.486329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43698062255'
down_revision = 'cff5e8520dd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
